name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, pdo_sqlite

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate APP_KEY
        run: |
          APP_KEY=$(php artisan key:generate --show)
          echo "APP_KEY=${APP_KEY}" >> .env

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Start Laravel Server
        run: php artisan serve --host=127.0.0.1 --port=8000 &
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite DB_DATABASE=$(pwd)/database/database.sqlite

      - name: Execute Tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          APP_ENV: testing
          DB_CONNECTION: sqlite DB_DATABASE=$(pwd)/database/database.sqlite
        run: php artisan test
